name: Hello Action

on: 
    push:
        branches: [ main ]

jobs:
    say-hello:
        runs-on: ubuntu-lastest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Print message
              run: echo "Hello, World!"
                